name: Windows

on: 
  push:
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest
    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        compiler: [mingw-w64, msvc16]
        bits: [32, 64]
        include:
        - compiler: mingw-w64
          bits: 32
          ARCH: "x86"
          COMPILER_PATH: "C:/msys64/mingw32/bin" 
        - compiler: mingw-w64
          bits: 64
          ARCH: "x64"
          COMPILER_PATH: "C:/msys64/mingw64/bin"  
        - compiler: msvc16
          bits: 32
          ARCH: "x86"
          VSBINPATH: "Win32" 
        - compiler: msvc16
          bits: 64
          ARCH: "x64" 
          VSBINPATH: "x64"
          
    env:
      RELEASE_NAME: raylib-3.1_win${{ matrix.bits }}_${{ matrix.compiler }}

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Setup Environment
      run: | 
        dir
        mkdir build
        cd build
        mkdir ${{ env.RELEASE_NAME }}
        cd ${{ env.RELEASE_NAME }}
        mkdir include
        mkdir lib
        cd ../../../raylib

    # Setup MSBuild.exe path if required
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.1
      if: matrix.compiler == 'msvc16'
   
    # TODO: Review x86 dynamic library building, linking does not work because x86 libraries are not available
    - name: Build Library (MinGW-w64)
      run: |
        cd src
        ${{ matrix.COMPILER_PATH }}/i686-w64-mingw32-gcc.exe -v
        ${{ matrix.COMPILER_PATH }}/mingw32-make PLATFORM=PLATFORM_DESKTOP CC="${{ matrix.COMPILER_PATH }}/i686-w64-mingw32-gcc.exe" RAYLIB_BUILD_ARCH=${{ matrix.ARCH }} RAYLIB_LIBTYPE=STATIC RAYLIB_RELEASE_PATH="../build/${{ env.RELEASE_NAME }}/lib"
        ${{ matrix.COMPILER_PATH }}/mingw32-make PLATFORM=PLATFORM_DESKTOP CC="${{ matrix.COMPILER_PATH }}/i686-w64-mingw32-gcc.exe" RAYLIB_BUILD_ARCH=${{ matrix.ARCH }} RAYLIB_LIBTYPE=SHARED RAYLIB_RELEASE_PATH="../build/${{ env.RELEASE_NAME }}/lib" -B
        cd ..
      shell: cmd
      if: matrix.compiler == 'mingw-w64' && matrix.bits == 32
      
    # Previous job should do 32bit and 64bit but there are config issues with the host-machine
    # TODO: Compile resource file raylib.dll.rc for linkage on raylib.dll generation
    - name: Build Library (MinGW-w64)
      run: |
        cd src
        gcc -v
        make PLATFORM=PLATFORM_DESKTOP CC=gcc RAYLIB_BUILD_ARCH=${{ matrix.ARCH }} RAYLIB_LIBTYPE=STATIC RAYLIB_RELEASE_PATH="../build/${{ env.RELEASE_NAME }}/lib"
        make PLATFORM=PLATFORM_DESKTOP CC=gcc RAYLIB_BUILD_ARCH=${{ matrix.ARCH }} RAYLIB_LIBTYPE=SHARED RAYLIB_RELEASE_PATH="../build/${{ env.RELEASE_NAME }}/lib"
        cd ..
      shell: cmd
      if: matrix.compiler == 'mingw-w64' && matrix.bits == 64
      
    - name: Build Library (MSVC16)
      run: |
        cd projects/VS2017
        msbuild.exe raylib.sln /target:raylib /property:Configuration=Release /property:Platform=${{ matrix.ARCH }}
        copy /Y .\bin\${{ matrix.VSBINPATH }}\Release\raylib.lib .\..\..\build\${{ env.RELEASE_NAME }}\lib\raylib.lib
        msbuild.exe raylib.sln /target:raylib /property:Configuration=Release.DLL /property:Platform=${{ matrix.ARCH }}
        copy /Y .\bin\${{ matrix.VSBINPATH }}\Release.DLL\raylib.dll .\..\..\build\${{ env.RELEASE_NAME }}\lib\raylib.dll
        copy /Y .\bin\${{ matrix.VSBINPATH }}\Release.DLL\raylib.lib .\..\..\build\${{ env.RELEASE_NAME }}\lib\raylibdll.lib
        cd ../..
      shell: cmd
      if: matrix.compiler == 'msvc16'
      
    - name: Generate Artifacts
      run: |
        copy /Y .\src\raylib.h .\build\${{ env.RELEASE_NAME }}\include\raylib.h
        cd build
        7z a ./${{ env.RELEASE_NAME }}.zip ./${{ env.RELEASE_NAME }}
        dir
      shell: cmd
        
    - name: Upload Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.RELEASE_NAME }}.zip
        path: ./build/${{ env.RELEASE_NAME }}.zip
        
    - name: Upload Artifact to Release
      uses: actions/upload-release-asset@v1.0.1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/${{ env.RELEASE_NAME }}.zip
          asset_name: ${{ env.RELEASE_NAME }}.zip
          asset_content_type: application/zip
      if: github.event_name == 'release' && github.event.action == 'published'
       
